name: Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      POSTGRES_IMAGE: "postgres:11.6-alpine"
      CLAIR_VERSION: "v2.1.7"
      CLAIR_LOCAL_SCAN_IMAGE: "arminc/clair-local-scan"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
          install: true

      - name: Build image
        run: docker build -t $CLAIR_LOCAL_SCAN_IMAGE --build-arg VERSION=$CLAIR_VERSION clair

      - name: Start Postgres
        run: |
          docker pull $POSTGRES_IMAGE
          docker run -d --name postgres -e 'PGDATA=/var/lib/postgresql/clair' -e POSTGRES_PASSWORD=password $POSTGRES_IMAGE
      - name: Run Clair
        run: |
          docker run --rm -d --link postgres:postgres -e PGPASSWORD=password $POSTGRES_IMAGE pg_isready -U postgres -h postgres
          docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE
      - name: Docker logs
        run: |
          docker logs clair
      - name: Checking
        run: |
          ./check.sh
      - name: Docker logs
        run: |
          docker logs clair
      - name: Tag images
        run: |
          docker stop clair
          docker stop postgres
          docker commit postgres arminc/clair-db:$(date +%Y-%m-%d)
          docker tag arminc/clair-db:$(date +%Y-%m-%d) arminc/clair-db:latest
          docker tag $CLAIR_LOCAL_SCAN_IMAGE ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${GITHUB_SHA}
          docker images
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push images
        run: |
          docker push ${CLAIR_LOCAL_SCAN_IMAGE}:${CLAIR_VERSION}_${GITHUB_SHA}
          docker push $CLAIR_LOCAL_SCAN_IMAGE:latest
          docker push arminc/clair-db:$(date +%Y-%m-%d)
          docker push arminc/clair-db:latest
